from pymongo import MongoClient
import random
import datetime
from faker import Faker

def seed_volunteers():
    client = MongoClient('mongodb+srv://Harry_123:Harry123@cluster0.whzu2ah.mongodb.net/janseva')
    db = client.janseva
    
    real_skills = db.volunteers.distinct("skills")
    real_domains = db.volunteers.distinct("domains")
    real_availability = db.volunteers.distinct("availability")
    
    if not real_skills or not real_domains or not real_availability:
        print("Required fields missing from existing DB. Please ensure DB is not completely empty.")
        return

    # Critical humanitarian skills weight more (e.g. Medical, First Aid, Rescue if present)
    skill_weights = []
    for skill in real_skills:
        if skill in ["Medical", "First Aid", "Rescue", "Logistics"]:
            skill_weights.append(5)
        else:
            skill_weights.append(1)

    print(f"Using Skills: {real_skills}")
    print(f"Using Domains: {real_domains}")
    print(f"Using Availability: {real_availability}")

    # Clear existing volunteers generated by earlier runs if we want clean state 
    # (But wait, we should only delete the volunteers with a specific marker to preserve manually created ones if any, 
    # but the prompt implies replacing the 500 block. Let's delete all role='volunteer')
    db.users.delete_many({"role": "volunteer", "email": {"$regex": "vol_ml"}})
    db.volunteers.delete_many({"userId": {"$in": [u['_id'] for u in db.users.find({"role": "volunteer", "email": {"$regex": "vol_ml"}})]}})

    # Use multiple locales for Indian regional diversity
    fake_hi = Faker('hi_IN')
    fake_en = Faker('en_IN')
    fake_ta = Faker('ta_IN') # Tamil
    fakers = [fake_hi, fake_en, fake_ta]
    
    volunteers_data = []
    users_data = []
    
    print("Generating 500 volunteers...")
    
    # Pre-generate Users
    for i in range(500):
        fake = random.choice(fakers)
        gender = random.choice(['Male', 'Female', 'Other'])
        user_doc = {
            "name": fake.name(),
            "email": f"vol_ml_{i}_{fake.user_name()}@test.com",
            "password": "hashed_password", # Dummy password
            "role": "volunteer",
            "isActive": True,
            "createdAt": datetime.datetime.now(datetime.UTC),
            "updatedAt": datetime.datetime.now(datetime.UTC)
        }
        users_data.append(user_doc)
        
    inserted_users = db.users.insert_many(users_data).inserted_ids
    
    # Generate Volunteers
    for i, user_id in enumerate(inserted_users):
        fake = random.choice(fakers)
        gender = random.choice(['Male', 'Female', 'Other'])
        num_skills = random.randint(2, 6)
        num_domains = random.randint(1, 3)
        
        selected_skills = random.choices(real_skills, weights=skill_weights, k=num_skills)
        selected_skills = list(set(selected_skills)) # unique
        selected_domains = random.sample(real_domains, min(num_domains, len(real_domains)))
        
        # Realistic Indian geo coordinates
        # Lat: 8.4 to 37.6, Lon: 68.7 to 97.25
        lat = round(random.uniform(8.4, 37.6), 4)
        lng = round(random.uniform(68.7, 97.25), 4)
        
        vol_doc = {
            "userId": user_id,
            "gender": gender,
            "age": random.randint(18, 65),
            "domains": selected_domains,
            "skills": selected_skills,
            "availability": random.choice(real_availability),
            "isAvailable": random.random() < 0.7, # 70% true
            "assignedRequests": [],
            "completedRequests": random.randint(0, 120),
            "surveysConducted": random.randint(0, 30),
            "volunteeringHours": random.randint(0, 2500),
            "rating": round(max(2.5, min(5.0, random.gauss(4.1, 0.4))), 1),
            "rank": None,
            "location": {
                "type": "Point",
                "coordinates": [lng, lat],
                "city": fake.city(),
                "state": fake.state()
            },
            "createdAt": datetime.datetime.now(datetime.UTC),
            "updatedAt": datetime.datetime.now(datetime.UTC)
        }
        volunteers_data.append(vol_doc)

    # Insert in batches of 50
    for i in range(0, 500, 50):
        db.volunteers.insert_many(volunteers_data[i:i+50])
        
    print("Inserted 500 volunteers.")
    print("Please run node src/utils/runScoring.js immediately to assign ranks/tiers.")

if __name__ == "__main__":
    seed_volunteers()
